### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by junyuchen245** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#15]
Thanks for the reply. I have been trying to replicate the result of VoxelMorph (haven't tried Transmorph yet). I have tested pre-trained weights in torch1.9 and it worked. So that is the most confusing part since I only changed the dataset path directory in the train_vxm.py. Will try more maybe.

_Originally posted by @tuffr5 in https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/issues/11#issuecomment-1086901195_

**Comment by junyuchen245** [comment]
Hi @tuffr5 ,

I tried VoxelMorph again using the same scripts that I provided for 11 epochs, and it seemed everything was working just fine:
![image](https://user-images.githubusercontent.com/17306891/161600206-cac33b49-3d24-44d7-ae67-ff841a0db11c.png)

Perhaps can you try pytorch 1.7 to see if it works?

Junyu

**Comment by tuffr5** [comment]
![image](https://user-images.githubusercontent.com/31501302/161603833-49ed3647-b63a-48f7-88ac-01408f455275.png)
[blue] VoxelMorph [red] TransMorph.

I will try pytorch 1.7 and see how that goes. Thank you so much.

**Comment by junyuchen245** [comment]
@tuffr5 Yep. That definitely doesn't look right. I'm wondering whether this is due to some type of pytorch update that affects the spatial transformation function. However, it seemed like the scripts worked fine under Pytorch 1.11.

Let me know how it goes.

Junyu

**Comment by tuffr5** [comment]
Sure. Thank you. I have tested 1.9 and 1.11 on my machine, and none of them works. I am testing 1.7 now and will report here.

**Comment by junyuchen245** [comment]
@tuffr5 Hmm... Interesting. I'll try replicating your problem with 1.9 and 1.11 once I have more time. Thanks for letting me know.
