### ISSUE TITLE
Evaluation in datasets oriented according to MNI152

### ISSUE THREAD

**Issue by moniquisma** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#16]
Dear author,

I have tried to evaluate the models trained on IXI datasets on a dataset that was initially oriented according to MNI152 space. 
Since the models have been trained with images oriented to OASIS space, should I notice a downgrade of the performance 
due to this or the method should provide competitive results no matter this initial alignment?

Best regards.

**Comment by junyuchen245** [comment]
Hi @moniquisma ,

That is correct. Both the IXI and OASIS datasets were normalized using FreeSurfer to Talairach space, which I think is different from MNI space. As a result, you should anticipate a potential performance degradation.

Thanks,
Junyu

**Comment by moniquisma** [comment]
Thank you so much for your reply. 
Do you know any code to transform an image oriented according to MNI space 
to OASIS space?

Thank you!!
