### ISSUE TITLE
Training problem of VoxelMorph on IXI

### ISSUE THREAD

**Issue by tzayuan** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#18]
Hi, @junyuchen245 

I'm sorry to bother you again, but I have some questions which I can't sove it on myself.

I tried to retrain voxelmorph on IXI dataset, but I found that the `dsc` can't be improved with the increase of epoch.The running code for training is download in your git without any modification(except data path). 

In addition, I downloaded your pretrained model and run `infer.py`, and the result is correct.

Here's my training log of 3 epoch:[logoffice .log](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/files/8509999/logoffice.log)
 

Code for training:[VM.zip](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/files/8510049/VM.zip)

Thanks a lot!!

Best regards, 
Ztayuan

**Comment by junyuchen245** [comment]
Hi @tzayuan ,

It is found that the VoxelMorph script currently only compatible with PyTorch 1.7 [see here](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/issues/15#issuecomment-1088012308). While I continue to investigate, you can test it on PyTorch 1.7 to see whether it works.

Junyu

**Comment by tzayuan** [comment]
Thanks for your suggestion, I will test it on PyTorch 1.7.

Hmmmm, that's sound interesting. Some low-level details may be involved, I've also very curious!!
