### ISSUE TITLE
TransMorph_affine

### ISSUE THREAD

**Issue by golnooshAbd** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#20]
Hi, @junyuchen245 
Is there any 2D version of the model "TransMorph_affine" available?
Thanks in advance.

**Comment by junyuchen245** [comment]
Hi @golnooshAbd ,

Unfortunately, we do not have the 2D version of the affine model. However, converting the script from 3D to 2D should be straightforward, but I don't have much time at the moment.

-Junyu
