### ISSUE TITLE
About Voxelmorph in your code

### ISSUE THREAD

**Issue by fanppp** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#21]
Hi, @junyuchen245 
Thank you so much for sharing your work with us !
I'm sorry to bother you,  but I have a question about VoxelMorph in your code.
Is there something wrong with the VoxelMorph reproduced in your code? It seems that the stride of the first convolutional layer in the original VoxelMorph is 1.

your code：
![image](https://user-images.githubusercontent.com/105860719/169289392-f6c4f6c1-82a2-40a0-b3cd-a2ac6f86890d.png)

Architecture of VoxelMorph：
![image](https://user-images.githubusercontent.com/105860719/169289438-690c3926-f033-48ed-97f1-cab5cd32f64e.png)

**Comment by junyuchen245** [comment]
Hi @fanppp ,

Thanks for your interest in our work. Note that we didn't reproduced the networks of the baselines. The VoxelMorph code was borrowed directly from: https://github.com/voxelmorph/voxelmorph/blob/master/voxelmorph/torch/networks.py, where you can see that the models in our repository and the ones in their official repository are consistent (maybe with some slight modifications to fit our training scripts).

Thanks,
Junyu

**Comment by fanppp** [comment]
> Hi @fanppp ,
> 
> Thanks for your interest in our work. Note that we didn't reproduce the networks of the baselines. The VoxelMorph code was borrowed directly from: https://github.com/voxelmorph/voxelmorph/blob/master/voxelmorph/torch/networks.py, where you can see that the models in our repository and the ones in their official repository are consistent (maybe with some slight modifications to fit our training scripts).
> 
> Thanks, Junyu

Oh, I got it, Thans for your reply.
