### ISSUE TITLE
TransMorph_affine

### ISSUE THREAD

**Issue by Yangxi12** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#23]
Hi @junyuchen245
    If an image pair has not been affinely aligned, an affine Transformer may be used prior to the deformable registration (left dashed box). It needs to use TransMorph_affine model. Is this right?
    And we need to use infer_affine.py to convert our train dataset to be aligned with our template image. Is this right?

**Comment by junyuchen245** [comment]
Hi @Yangxi12 ,

Sorry for the delayed response. We did not provide pre-trained weights for the affine model. To use TransMorph_affine, you'll need to train it from scratch using your own data. This should be fairly simple, as the training itself is self-supervised.

Junyu
