### ISSUE TITLE
Which script should be run?

### ISSUE THREAD

**Issue by tracob-github** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#24]
Thank you so much for sharing your work!

Since the script in the IXI folder is for brain atlas registration. But I want to perform registration between patients, so which script should I run?

**Comment by junyuchen245** [comment]
Hi @tracob-github ,

Yes, the scripts in the IXI folder are for atlas-to-patient registration. You can take a look at the scripts in the OASIS for inter-patient registration.

Thanks,
Junyu
