### ISSUE TITLE
Prostate

### ISSUE THREAD

**Issue by jakubMitura14** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#26]
Hello thanks for publishing your algorithm !! Can i use it also for multimodal prostate mri ? Or it deoends on some average brain image ?

**Comment by junyuchen245** [comment]
Hi @jakubMitura14 ,

Thanks for your interest in our work! 
The answer is yes, but you'll need to retrain the network for prostate MRI registration using your own data.

Thanks,
Junyu
