### ISSUE TITLE
Transmorph paper

### ISSUE THREAD

**Issue by kiwibruyant** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#28]
Hello,

I'm wondering what is the library used in the paper to display the Dice scores as box plots in the result part. And is it possible to get a code snippet ?

Thanks in advance

**Comment by junyuchen245** [comment]
Hi @kiwibruyant ,

Please check out this script for the plots:
https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/main/IXI/analysis.py

Junyu
