### ISSUE TITLE
About 2D registration

### ISSUE THREAD

**Issue by HilbertMaximov** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#29]
Dear author:
I noticed that you developed this method of 2D registration, I would like to know if the moving and fixed images in your code correspond to the train_dir and val_dir folders? (I have applied for Rafd dataset, but there is no reply)I want to use the following 1440*1440 png format image to do registration, how should I modify your code? Sincerely looking forward to your reply!
such as
moving:
![SkyViewPACS_Image 1 2 840 113619 2 327 3 279713030 420 1406506826 183 17 16](https://user-images.githubusercontent.com/59821328/175814246-a3e06655-5bdf-4f2c-8744-af7c86bd6eb2.png)
![SkyViewPACS_Image 1 2 840 113619 2 327 3 279713030 420 1406506826 183 18 17](https://user-images.githubusercontent.com/59821328/175814256-e6c86960-48ea-407e-983d-a330fc015ff5.png)
fixed:
![SkyViewPACS_Image 1 2 840 113704 1 111 4012 1403001136 14187 10](https://user-images.githubusercontent.com/59821328/175814325-19ac44ce-fa91-48ae-93c7-a8c92b80d63e.png)

**Comment by junyuchen245** [comment]
Hi @HilbertMaximov ,

Sorry for the delayed reply.

You will need to use the 2D version of TransMorph: https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/tree/main/RaFD/TransMorph2D
You will then need to modify the dataset scripts to load your png images.

-Junyu

**Comment by loladidi** [comment]
> 尊敬的作者：我注意到您开发了这种 2D 配准方法，我想知道您的代码中的移动和固定图像是否对应于 train_dir 和 val_dir 文件夹？（我已经申请了Rafd数据集，但没有回复）我想使用以下 1440*1440 png 格式的图片进行注册，我应该如何修改您的代码？真诚期待您的回复！如搬家： ![SkyViewPACS_Image 1 2 840 113619 2 327 3 279713030 420 1406506826 183 17 16](https://user-images.githubusercontent.com/59821328/175814246-a3e06655-5bdf-4f2c-8744-af7c86bd6eb2.png) ![SkyViewPACS_Image 1 2 840 113619 2 327 3 279713030 420 1406506826 183 18 17](https://user-images.githubusercontent.com/59821328/175814256-e6c86960-48ea-407e-983d-a330fc015ff5.png)固定： ![SkyViewPACS_Image 1 2 840 113704 1 111 4012 1403001136 14187 10](https://user-images.githubusercontent.com/59821328/175814325-19ac44ce-fa91-48ae-93c7-a8c92b80d63e.png)

Hello, have you resolved this issue? How should the dataset be allocated?

**Comment by xiaomudsg** [comment]
> 嗨，
> 
> 很抱歉延迟回复。
> 
> 您将需要使用 TransMorph 的 2D 版本： https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/tree/main/RaFD/TransMorph2D 然后，您需要修改数据集脚本以加载 png 图像。



> Dear author: I noticed that you developed this method of 2D registration, I would like to know if the moving and fixed images in your code correspond to the train_dir and val_dir folders? (I have applied for Rafd dataset, but there is no reply)I want to use the following 1440*1440 png format image to do registration, how should I modify your code? Sincerely looking forward to your reply! such as moving: ![SkyViewPACS_Image 1 2 840 113619 2 327 3 279713030 420 1406506826 183 17 16](https://user-images.githubusercontent.com/59821328/175814246-a3e06655-5bdf-4f2c-8744-af7c86bd6eb2.png) ![SkyViewPACS_Image 1 2 840 113619 2 327 3 279713030 420 1406506826 183 18 17](https://user-images.githubusercontent.com/59821328/175814256-e6c86960-48ea-407e-983d-a330fc015ff5.png) fixed: ![SkyViewPACS_Image 1 2 840 113704 1 111 4012 1403001136 14187 10](https://user-images.githubusercontent.com/59821328/175814325-19ac44ce-fa91-48ae-93c7-a8c92b80d63e.png)

May I ask if you finally modified the dataset to load png images?

**Comment by 1chuanchuan** [comment]
> 尊敬的作者： 我注意到您开发了这种 2D 配准方法，我想知道您代码中的移动和固定图像是否对应于 train_dir 和 val_dir 文件夹？（我已经申请了 Rafd 数据集，但没有回复）我想使用以下 1440*1440 png 格式的图片进行注册，我应该如何修改您的代码？衷心期待您的回复！如移动： ![SkyViewPACS_Image 1 2 840 113619 2 327 3 279713030 420 1406506826 183 17 16](https://user-images.githubusercontent.com/59821328/175814246-a3e06655-5bdf-4f2c-8744-af7c86bd6eb2.png) ![SkyViewPACS_Image 1 2 840 113619 2 327 3 279713030 420 1406506826 183 18 17](https://user-images.githubusercontent.com/59821328/175814256-e6c86960-48ea-407e-983d-a330fc015ff5.png)固定： ![SkyViewPACS_Image 1 2 840 113704 1 111 4012 1403001136 14187 10](https://user-images.githubusercontent.com/59821328/175814325-19ac44ce-fa91-48ae-93c7-a8c92b80d63e.png)

Hello, did you finally solve this problem? I would like to know how to modify the code to read png images?
