### ISSUE TITLE
How many labels are there in the IXI dataset?

### ISSUE THREAD

**Issue by bhosalems** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#30]
I am reimplementing code of VoxelMorph and testing it on the IXI dataset. I am curious as to how many classes should be there. I see there are many segmentation labels as given here https://github.com/junyuchen245/Preprocessed_IXI_Dataset/blob/main/label_info.txt but from the voxelmorph-related code in the repo, I see that the number of labels is 46. 

Can you please confirm this?

Because while one hot encoding the labels I getting error in the below code,
` fixed_label = torch.nn.functional.one_hot(fixed_label.long(), num_classes=self.n_class).float()`
as
`RuntimeError: Class values must be smaller than num_classes.`

**Comment by junyuchen245** [comment]
Hi @bhosalems ,

There are in excess of 46 labels, however, we have only evaluated those that are used in the VoxelMorph paper. Check out this example:
https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/main/IXI/Results/Vxm_1_ncc_1_diffusion_1.csv

https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/dfa24a47a564a000aa9b4eea95a6e83a24568359/IXI/analysis.py#L24-L25

Our VoxelMorph models were borrowed directly from their official repository, so you don't really have to reimplement them.

Junyu

**Comment by bhosalems** [comment]
Thanks for the reply; But while calculating the dice score in the function below I see that it used around 30 labels.
```
def dice_val_VOI(y_pred, y_true):
    VOI_lbls = [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 34, 36]
    pred = y_pred.detach().cpu().numpy()[0, 0, ...]
    true = y_true.detach().cpu().numpy()[0, 0, ...]
    DSCs = np.zeros((len(VOI_lbls), 1))
    idx = 0
    for i in VOI_lbls:
        pred_i = pred == i
        true_i = true == i
        intersection = pred_i * true_i
        intersection = np.sum(intersection)
        union = np.sum(pred_i) + np.sum(true_i)
        dsc = (2.*intersection) / (union + 1e-5)
        DSCs[idx] =dsc
        idx += 1
    return np.mean(DSCs)
```

**Comment by xychen2022** [comment]
> Hi @bhosalems ,
> 
> There are in excess of 46 labels, however, we have only evaluated those that are used in the VoxelMorph paper. Check out this example: https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/main/IXI/Results/Vxm_1_ncc_1_diffusion_1.csv
> 
> https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/dfa24a47a564a000aa9b4eea95a6e83a24568359/IXI/analysis.py#L24-L25
> 
> Our VoxelMorph models were borrowed directly from their official repository, so you don't really have to reimplement them.
> 
> Junyu

Nice work and thanks for providing your pretrained model weights and testing results, which are very helpful. My question is the average DSC reported in Table 3 is based on this subset of structures? I noticed that the overall mean DSC is around 0.57.
