### ISSUE TITLE
Preprocessed dataset doesn't contain  x_seg, y_seg 

### ISSUE THREAD

**Issue by CarrierDiagnostics** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#32]
Hello

Your preprocessed data pkl files only contain a tuple with img and label, so this line doesn't work:

x, y, x_seg, y_seg = pkload(path)

regards
Jason

**Comment by junyuchen245** [comment]
Hi @CarrierDiagnostics ,

Sorry for the delayed reply!

This repository has several different versions of data loaders. Please be sure you are using the right one.

Junyu
