### ISSUE TITLE
how to change input shape in model?

### ISSUE THREAD

**Issue by nightandweather** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#34]
Hello JunyuChen

Thank you for sharing your works!

I'm interested in other **morph to Hnscc rt data.

I'm already to make dicom to pickle file. In order to enter the model, resize it in the input shape model, but it does not seem to learn well.
I'm trying to fix the data size (512,512,200) to (160,192,224) and I don't think the model is learning(It seems that loss is not falling, and learning is not working.). Where should I fix it?

**Comment by junyuchen245** [comment]
Hi @nightandweather ,

Sorry for the delayed reply.

For TransMorph, you can change image shape in config.par. However, to use the default setting, the shapes must be divisible by 32. For all others, image shapes can be modified in the training scripts.

Junyu
