### ISSUE TITLE
Training problems on the IXI dataset

### ISSUE THREAD

**Issue by Yongxin1120** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#36]
Hi,

I encountered some difficulties in training the model, I tried to use the preprocessed IXI dataset for model training, including "VoxelMorph", "CycleMorph", "TransMorph", but all encountered the same problem: "ValueError: num_samples should be a positive integer value, But got num_samples=0 "This problem appears in the train.py file" train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True, Num_workers =4, pin_memory=True) ", I found that I could fix this by setting shuffle=Flase, but then a new problem appeared: "UnboundLocalError: Local variable 'def_out' referenced Before Assignment ", this problem appears in the train.py file "pred_fig = comput_fig(def_out)". I can't deal with this new problem. I would like to ask you for help. Maybe I cannot modify the shuffle parameter in the source program. What is the cause and solution of the first problem? I've been using both my laptop and workstation, so I rule out the possibility of hardware causing the problem.

Best

Yongxin

![image](https://user-images.githubusercontent.com/111277559/188781348-9b142637-ef04-4367-9205-479bdaae9fa2.png)

![image](https://user-images.githubusercontent.com/111277559/188781285-99244a78-a5fd-4c46-88dd-cab2042a56e2.png)

![image](https://user-images.githubusercontent.com/111277559/188775272-e4532d80-317c-4a45-bfed-0380bd08e14c.png)

![image](https://user-images.githubusercontent.com/111277559/188775189-057bed47-9646-44fa-a8b8-c0363ad84259.png)

**Comment by junyuchen245** [comment]
Hi @Yongxin1120 ,

It is very likely that you didn't set training and validation folder correctly. This error occurs because the folders that contains training and validation datasets are empty.

Junyu

**Comment by Yongxin1120** [comment]
> Hi @Yongxin1120 ,
> 
> It is very likely that you didn't set training and validation folder correctly. This error occurs because the folders that contain training and validation datasets are empty.
> 
> Junyu

Hi Junyu

Thank you very much for your reply, but this problem should not exist, because I have used the data set you provided and modified the corresponding path. I will check the data problem you raised in detail again.

Best
Yongxin

**Comment by junyuchen245** [comment]
@Yongxin1120 It maybe useful to try print(glob.glob(train_dir+'*.pkl')) and see if it prints all the file names.

Junyu

**Comment by Yongxin1120** [comment]
> 

Hi Junyu

Thank you very much for your careful help. I'll try it now

Best 

Yongxin
