### ISSUE TITLE
Memory problems during model training and testing

### ISSUE THREAD

**Issue by Yongxin1120** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#38]
Hi Junyu

Thanks for your help. Recently we encountered some memory problems during model training and testing. As shown in the picture, on our workstation, we are using an NVIDIA RTX A2000 graphics card with 12GB of video memory, but it still prompts that there is not enough memory. I would like to ask what configuration of video card is required to run this model, and whether there is a way to reduce the amount of video memory needed to run this model.

Best regards

Yongxin

<img width="812" alt="cece5c87b0e6a8c987423515c414d14" src="https://user-images.githubusercontent.com/111277559/190076879-f9184be5-3e89-48d3-8bd9-8dd547539ad9.png">

**Comment by junyuchen245** [comment]
Hi @Yongxin1120 ,

Enabling the checkpointing flag can help save memory. Additionally, we will be providing a script that works on 16FP in the future. With the image size of the IXI dataset, the memory usage should be well under 10GB.
https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/9c34ac92ec4626c88714fd2336aaff59c163e626/IXI/TransMorph/models/configs_TransMorph.py#L51

Thanks,
Junyu
