### ISSUE TITLE
Problems of running traditional registration methods such as NiftyReg and SyNc on the IXI dataset

### ISSUE THREAD

**Issue by Yongxin1120** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#39]
Dear author Hello, I am interested in the effect of traditional registration methods such as NiftyReg and SyNc provided by your team on the IXI dataset, but I have encountered some difficulties when trying to reproduce. Could you please provide a running example to let me know how to run the traditional registration method codes such as NiftyReg and SyNc provided by you? (These are not in the help document)

**Comment by junyuchen245** [comment]
Hi @Yongxin1120 ,

I apologize for the delay in my response. Could you please provide more details on the specific problems you encountered?

Thanks,
Junyu
