### ISSUE TITLE
RaFD dataset preprocessing

### ISSUE THREAD

**Issue by Jun-electrophysiology** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#40]
Hi,

Thanks for your wonderful work. I'd like to use the TransMorph as a baseline. I noticed that you used the PKL file in your code (RaFD -> TransMorph2D -> train_TransMorph.py).

Job done.

**Comment by koalabrain** [comment]
我也遇到了相同的问题，怎样把数据处理成input所需的pkl，你找到解决方法了吗？

**Comment by Jun-electrophysiology** [comment]
> 我也遇到了相同的问题，怎样把数据处理成input所需的pkl，你找到解决方法了吗？

处理成pkl文件，还好。用下面代码“write_pickle”处理的。就是不知道原作者是把哪些样本划分成了验证集和测试集，可能才好更公平的对比。
from batchgenerators.utilities.file_and_folder_operations import *
def write_pickle(obj, file: str, mode: str = 'wb') -> None:
    with open(file, mode) as f:
        pickle.dump(obj, f)

**Comment by loladidi** [comment]
k

**Comment by loladidi** [comment]
> 我也遇到了相同的问题，怎样把数据处理成input所需的pkl，你找到解决方法了吗？

Hello, may I ask if your issue has been resolved

**Comment by loladidi** [comment]
> 你好
> 
> 感谢您的出色工作。我想使用 TransMorph 作为基准。我注意到您在代码中使用了 PKL 文件（RaFD -> TransMorph2D -> train_TransMorph.py）。
> 
> 工作完成。

Hello, have you resolved this issue? How was it resolved?

**Comment by 1chuanchuan** [comment]
> 我也遇到了相同的问题，怎样把数据处理成input所需的pkl，你找到解决方法了吗？

Hello, have you solved this problem? I would like to know how you converted the images in the input folder to.pkl format.
