### ISSUE TITLE
about environment

### ISSUE THREAD

**Issue by amberhappy** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#41]
Hi, can you share the environmnet list? about Python and python-package version?

**Comment by junyuchen245** [comment]
Hi @amberhappy 

Here are the requirements.txt from three of our workstations:
https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/issues/11#issuecomment-1086774471

Junyu

**Comment by amberhappy** [comment]
Training script runs normally now. Thank you so much!
