### ISSUE TITLE
Plural in module import singular in filename

### ISSUE THREAD

**Issue by halidziya** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#52]
https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/639e1fc134e1cbc61c78a1e054cfcb6f4bafee38/TransMorph_affine/TransMorph_affine.py#LL25C25-L25C25

**Comment by junyuchen245** [comment]
Hi @halidziya,

Thanks for letting me know. It has been updated.

Junyu
