### ISSUE TITLE
label_info.txt

### ISSUE THREAD

**Issue by FuratAljishi** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#65]
Hi, can you explain the label_into.text? I am working with a custom dataset and reached the testing part infer_TransMorph.py, but got an error because I don't have my own version of the label_info.text.

**Comment by junyuchen245** [comment]
Hi @FuratAljishi ,

The "label_info.txt" file is essentially the FreeSurfer's label lookup table [(see here)](https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/AnatomicalROI/FreeSurferColorLUT), providing names for anatomical structures based on their label numbers. The script can be modified to bypass the use of this file.

Junyu
