### ISSUE TITLE
Training on 2D dataset.

### ISSUE THREAD

**Issue by MingR-Ma** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#8]
Hi, I want to train TransfMorph on a 2D dataset shaped of [112,112]. But I found that your project does not support training on 2D images. How should I modify your code?

**Comment by HilbertMaximov** [comment]
> 嗨@MingR马 ，
> 
> 我们确实有一个2D TransMorph。我们在2D [RaFD数据集](https://rafd.socsci.ru.nl/RaFD2/RaFD?p=main)上评估了TransMorph，并期望在下个月在此github存储库上发布结果。同时，您可以使用我刚刚[在此处](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/tree/main/RaFD/TransMorph2D)上传的脚本。
> 
> 请注意，112 不是 TransMorph 默认配置的有效大小，该配置具有四个缩减采样步骤。最后一个块将输入图像的采样率降低 32 倍。为了缓解这种情况，您可以将图像填充到160x160的大小（您还需要在配置文件中更改窗口大小）。或者，您可以尝试通过在此处修改配置文件来删除底部块：
> 
> https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/2a051bc7de5e95ba252decb1769911e1d12cd1fa/RaFD/TransMorph2D/models/configs_TransMorph.py#L39-L40
> 
> 
> https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/2a051bc7de5e95ba252decb1769911e1d12cd1fa/RaFD/TransMorph2D/models/configs_TransMorph.py#L52
> 
> 谢谢，俊宇

Dear author:
I noticed that you developed this method of 2D registration, I would like to know if the moving and fixed images in your code correspond to the train_dir and val_dir folders? (I have applied for Rafd dataset, but there is no reply)I want to use the following 1440*1440 png format image to do registration, how should I modify your code?  Sincerely looking forward to your reply!
such as
moving:
![SkyViewPACS_Image 1 2 840 113619 2 327 3 279713030 420 1406506826 183 17 16](https://user-images.githubusercontent.com/59821328/175814045-ebc84649-973d-453b-9ecd-f483ffa1b2ba.png)
![SkyViewPACS_Image 1 2 840 113619 2 327 3 279713030 420 1406506826 183 18 17](https://user-images.githubusercontent.com/59821328/175814062-b6155315-2f93-45cf-a647-2f33405c3f8b.png)
fixed:
![SkyViewPACS_Image 1 2 840 113704 1 111 4012 1403001136 14187 10](https://user-images.githubusercontent.com/59821328/175814075-5b3438c0-1176-4363-bec0-b379e0c8d871.png)

**Comment by xiaomudsg** [comment]
> > 嗨@mingR马 ，
> > 我们确实有一个2D TransMorph。我们在2D [RaFD数据集](https://rafd.socsci.ru.nl/RaFD2/RaFD?p=main)上评估了TransMorph，并期望在下个月在此github存储库上发布结果。同时，您可以使用我刚刚[在此处](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/tree/main/RaFD/TransMorph2D)上传的脚本。
> > 请注意，112 不是 TransMorph 默认配置的有效大小，该配置具有四个缩减采样步骤。最后一个块将输入图像的采样率降低 32 倍。为了缓解这种情况，您可以将图像填充到160x160的大小（您还需要在配置文件中更改窗口大小）。或者，您可以尝试通过在此处修改配置文件来删除底部块：
> > https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/2a051bc7de5e95ba252decb1769911e1d12cd1fa/RaFD/TransMorph2D/models/configs_TransMorph.py#L39-L40
> > 
> > https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/2a051bc7de5e95ba252decb1769911e1d12cd1fa/RaFD/TransMorph2D/models/configs_TransMorph.py#L52
> > 
> > 谢谢，俊宇
> 
> 尊敬的作者：我注意到您开发了这种 2D 配准方法，我想知道您代码中的移动和固定图像是否对应于 train_dir 和 val_dir 文件夹？（我已申请Rafd数据集，但没有回复）我想使用以下1440*1440 png格式的图片进行注册，我应该如何修改您的代码？真诚期待您的回复！如移动： ![SkyViewPACS_Image 1 2 840 113619 2 327 3 279713030 420 1406506826 183 17 16](https://user-images.githubusercontent.com/59821328/175814045-ebc84649-973d-453b-9ecd-f483ffa1b2ba.png) ![SkyViewPACS_Image 1 2 840 113619 2 327 3 279713030 420 1406506826 183 18 17](https://user-images.githubusercontent.com/59821328/175814062-b6155315-2f93-45cf-a647-2f33405c3f8b.png)固定： ![SkyViewPACS_Image 1 2 840 113704 1 111 4012 1403001136 14187 10](https://user-images.githubusercontent.com/59821328/175814075-5b3438c0-1176-4363-bec0-b379e0c8d871.png)

May I ask if you finally solved the problem? I would like to use this method to align images in jpg format, but do not have the relevant code and wonder if you solved the problem?

**Comment by wangsh7** [comment]
> > 你好@mingR马 ，
> > 我们确实有一个 2D TransMorph。我们在 2D [RaFD 数据集](https://rafd.socsci.ru.nl/RaFD2/RaFD?p=main)上评估了 TransMorph，并期望在下个月在 github 存储库上发布结果。同时，您可以使用我刚刚[在此处](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/tree/main/RaFD/TransMorph2D)上传的脚本。
> > 请注意，112 不是 TransMorph 配置默认配置的有效大小，该有四个缩小采样步骤。最后一块将输入图像的采样率降低 32 倍。为了解决这种情况，您可以将图像填充到 160x160 的大小（您还需要在配置文件中更改窗口大小）。或者，您可以尝试通过在此处修改配置文件来删除底部块：
> > https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/2a051bc7de5e95ba252decb1769911e1d12cd1fa/RaFD/TransMorph2D/models/configs_TransMorph.py#L39-L40
> > 
> > https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/2a051bc7de5e95ba252decb1769911e1d12cd1fa/RaFD/TransMorph2D/models/configs_TransMorph.py#L52
> > 
> > 谢谢，俊宇
> 
> 尊敬的作者： 我注意到您开发了这种2D配准方法，我想知道您代码中的移动图像和固定图像是否对应于train_dir和val_dir文件夹？ （我已经申请了Rafd数据集，但没有回复）我想使用下面的1440*1440 png格式的图片进行注册，我应该如何修改你的代码？真诚期待您的回复！ 如 移动： 固定： ![SkyViewPACS_图像 1 2 840 113619 2 327 3 279713030 420 1406506826 183 17 16](https://user-images.githubusercontent.com/59821328/175814045-ebc84649-973d-453b-9ecd-f483ffa1b2ba.png) ![SkyViewPACS_图像 1 2 840 113619 2 327 3 279713030 420 1406506826 183 18 17](https://user-images.githubusercontent.com/59821328/175814062-b6155315-2f93-45cf-a647-2f33405c3f8b.png) ![SkyViewPACS_图像 1 2 840 113704 1 111 4012 1403001136 14187 10](https://user-images.githubusercontent.com/59821328/175814075-5b3438c0-1176-4363-bec0-b379e0c8d871.png)

What dataset did you use? Could you please share it?
