### ISSUE TITLE
Can this model be used for 2d image registration?

### ISSUE THREAD

**Issue by davesteps** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#81]
Hi, Is it possible to use this model for 2d image registration?

**Comment by junyuchen245** [comment]
Hi @davesteps,
 
For 2D registration, you will need to retrain the model using your own data. The necessary scripts can be found at the link: https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/tree/main/RaFD/TransMorph2D.

Junyu

**Comment by davesteps** [comment]
Thankyou
