### ISSUE TITLE
What are the corresponding classes for VoxelMorph-1 and VoxelMorph-2?

### ISSUE THREAD

**Issue by tuffr5** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#9]

**Comment by junyuchen245** [comment]
Hi @tuffr5 ,

Sorry but I'm a bit confused. What do you mean by classes?

Thanks,
Junyu

**Comment by tuffr5** [comment]
Thanks for the reply. Here I mean the Python Classes. And What are the differences? One is the MICCAI version and another is the CVPR version?

**Comment by tuffr5** [comment]
If I understand correctly, VoxelMorph_1 is VxmDense_1 in the models.py, VoxelMorph_2 is VxmDense_2, right?

I have download the pre-trained VoxelMorph_1 (_VoxelMorph_1_Validation_dsc0.720.pth.tar_) on the IXI dataset, and run the infer code. Here is my result:
![image](https://user-images.githubusercontent.com/31501302/160685267-f25d56b0-f9e1-456f-8bb7-4b1acafcc059.png)

This result is not consistent with the result reported in the README. Am I doing something wrong? Thanks for your time.

**Comment by junyuchen245** [comment]
Hi @tuffr5 ,

VoxelMorph-1 and -2 are the VoxelMorph variants introduced in the CVPR version: https://openaccess.thecvf.com/content_cvpr_2018/papers/Balakrishnan_An_Unsupervised_Learning_CVPR_2018_paper.pdf

If you are looking for the MICCAI version of VoxelMorph, please check [VoxelMorph-diff](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/tree/main/Baseline_registration_models/VoxelMorph-diff).

In terms of the results you obtained, the infer scripts averaged the results across all anatomical structures in the left and right brain. The results in the paper or README, however, were achieved by considering each anatomical component in the left and right brain as a single structure (e.g., left Left-Cerebral-White-Matter and Right-Cerebral-White-Matter -> Cerebral-White-Matter). I believe VoxelMorph and CylceMorph papers did the same thing.

To replicate our results, you can copy the corresponding `.csv` file generated by `infer.py`  (in the Quantitative_Results folder) into [Results folder](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/tree/main/IXI/Results) and run [`analysis.py`](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/main/IXI/analysis.py)

Thanks,
Junyu

**Comment by tuffr5** [comment]
Thanks for the reply.
